export const FETCH_INITIAL_PRICES_SUCCESS = 'FETCH_INITIAL_PRICES_SUCCESS';
export const FETCH_INITIAL_PRICES_FAILURE = 'FETCH_INITIAL_PRICES_FAILURE';
export const FETCH_INITIAL_PRICES_REQUESTED = 'FETCH_INITIAL_PRICES_REQUESTED';